//
// Created by ASUS on 9.05.2026.
//

#ifndef HAVALIMANI_YONETIM_SISTEMI1_HAVAYOLUSISTEMI_H
#define HAVALIMANI_YONETIM_SISTEMI1_HAVAYOLUSISTEMI_H


class HavayoluSistemi {
};


#endif //HAVALIMANI_YONETIM_SISTEMI1_HAVAYOLUSISTEMI_H